package discover

import (
	"context"
	"errors"
	"io/fs"
	"math/rand"
	"os"
	"path/filepath"
	"reflect"
	"syscall"
	"testing"
	"time"

	gitignore "github.com/boyter/gocodewalker/go-gitignore"
)

const fixtures = "../../testdata/fixtures"

// entry is the part of a File that classification decides.
type entry struct {
	Path string
	Set  SourceSet
}

func entries(tree *Tree) []entry {
	out := make([]entry, 0, len(tree.Files))
	for _, f := range tree.Files {
		out = append(out, entry{f.Path, f.Set})
	}
	return out
}

// shape is the part of a Tree that a walk decides, without the parsed syntax.
type shape struct {
	Root, Module  string
	Files         []entry
	NestedModules []string
	Coverage      map[SourceSet]SetCoverage
}

func shapeOf(tree *Tree) shape {
	return shape{tree.Root, tree.Module, entries(tree), tree.NestedModules, tree.Coverage}
}

// zeroCoverage returns coverage with every set at zero, then applies the given file counts.
func zeroCoverage(files map[SourceSet]int) map[SourceSet]SetCoverage {
	out := map[SourceSet]SetCoverage{}
	for _, set := range AllSets() {
		out[set] = SetCoverage{Files: files[set]}
	}
	return out
}

func walk(t *testing.T, root string, opts Options) *Tree {
	t.Helper()
	tree, err := Walk(context.Background(), root, opts)
	if err != nil {
		t.Fatalf("Walk(%s): %v", root, err)
	}
	return tree
}

// write creates files under root from a map of slash paths to contents.
func write(t *testing.T, root string, files map[string]string) {
	t.Helper()
	for path, content := range files {
		abs := filepath.Join(root, filepath.FromSlash(path))
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(abs, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

func TestWalkSetsFixture(t *testing.T) {
	root, err := filepath.Abs(filepath.Join(fixtures, "sets"))
	if err != nil {
		t.Fatal(err)
	}
	tree := walk(t, root, Options{})

	want := shape{
		Root:   root,
		Module: "example.com/sets",
		Files: []entry{
			// A file name that starts with a dot or an underscore is excluded, as the Go tool ignores it.
			{".gitignore", Excluded},
			{".hidden.go", Excluded},
			{".hidden/h.go", Excluded},
			{"README.md", Unsupported},
			{"_skip.go", Excluded},
			{"_skip/s.go", Excluded},
			{"a.go", Production},
			{"a_test.go", Test},
			{"gen.go", Generated},
			{"go.mod", Unsupported},
			{"nested/.gitignore", Excluded},
			{"nested/keep.go", Production},
			{"testdata/t.go", Testdata},
			{"vendor/x/x.go", Vendored},
		},
		NestedModules: []string{"tools/gen"},
		Coverage: zeroCoverage(map[SourceSet]int{
			Production: 2, Test: 1, Generated: 1, Vendored: 1,
			Testdata: 1, Excluded: 6, Unsupported: 2,
		}),
	}
	if got := shapeOf(tree); !reflect.DeepEqual(got, want) {
		t.Errorf("tree:\n got %+v\nwant %+v", got, want)
	}
}

func TestWalkEmptyFixture(t *testing.T) {
	root, err := filepath.Abs(filepath.Join(fixtures, "empty"))
	if err != nil {
		t.Fatal(err)
	}
	want := shape{
		Root:          root,
		Module:        "example.com/empty",
		Files:         []entry{{"go.mod", Unsupported}},
		NestedModules: []string{},
		Coverage:      zeroCoverage(map[SourceSet]int{Unsupported: 1}),
	}
	if got := shapeOf(walk(t, root, Options{})); !reflect.DeepEqual(got, want) {
		t.Errorf("tree:\n got %+v\nwant %+v", got, want)
	}
}

func TestWalkRootIsAbsoluteAndClean(t *testing.T) {
	tree := walk(t, filepath.Join(fixtures, "empty")+"/./", Options{})
	if !filepath.IsAbs(tree.Root) || filepath.Clean(tree.Root) != tree.Root {
		t.Errorf("root %q is not absolute and clean", tree.Root)
	}
}

func TestWalkOptions(t *testing.T) {
	root := t.TempDir()
	write(t, root, map[string]string{
		"internal/gen/x.go":      "package gen\n",
		"internal/testutil/u.go": "package testutil\n",
		"main.go":                "package main\n",
	})
	tree := walk(t, root, Options{
		Exclude:      []string{"internal/gen/**"},
		TestPatterns: []string{"internal/testutil/**"},
	})
	want := []entry{
		{"internal/gen/x.go", Excluded},
		{"internal/testutil/u.go", Test},
		{"main.go", Production},
	}
	if got := entries(tree); !reflect.DeepEqual(got, want) {
		t.Errorf("files = %v, want %v", got, want)
	}
	if tree.Module != "" {
		t.Errorf("module = %q, want empty without go.mod", tree.Module)
	}
}

func TestWalkRuleOrder(t *testing.T) {
	root := t.TempDir()
	write(t, root, map[string]string{
		// testdata wins over vendored, and vendored wins over excluded.
		"vendor/testdata/a.go": "package a\n",
		".x/vendor/b.go":       "package b\n",
		// excluded wins over unsupported.
		"_y/notes.txt": "notes\n",
		// generated wins over test.
		"g_test.go": "// Code generated by x. DO NOT EDIT.\n\npackage p\n",
		// test patterns never claim a non-Go file.
		"t/data.json": "{}\n",
	})
	tree := walk(t, root, Options{TestPatterns: []string{"t/**"}})
	want := []entry{
		{".x/vendor/b.go", Vendored},
		{"_y/notes.txt", Excluded},
		{"g_test.go", Generated},
		{"t/data.json", Unsupported},
		{"vendor/testdata/a.go", Testdata},
	}
	if got := entries(tree); !reflect.DeepEqual(got, want) {
		t.Errorf("files = %v, want %v", got, want)
	}
}

func TestWalkGitignore(t *testing.T) {
	root := t.TempDir()
	write(t, root, map[string]string{
		".gitignore":      "*.log\nout/\n/x.go\n**/tmp/\nspace.go\\ \n",
		"a.log":           "x\n",
		"out/b.go":        "package out\n",
		"x.go":            "package p\n",
		"sub/x.go":        "package sub\n",
		"deep/a/tmp/t.go": "package tmp\n",
		"space.go":        "package p\n",
		"sub/.gitignore":  "!keep.log\n",
		"sub/keep.log":    "x\n",
		"sub/drop.log":    "x\n",
		"sub/c.go":        "package sub\n",
	})
	// The escaped pattern names a file whose name ends in a space.
	write(t, root, map[string]string{"space.go" + " ": "package p\n"})
	tree := walk(t, root, Options{})
	want := []entry{
		{".gitignore", Excluded},
		// The escaped trailing space belongs to the pattern, so the walk keeps "space.go".
		{"space.go", Production},
		{"sub/.gitignore", Excluded},
		{"sub/c.go", Production},
		{"sub/keep.log", Unsupported},
		// The anchored pattern "/x.go" matches only at the root.
		{"sub/x.go", Production},
	}
	if got := entries(tree); !reflect.DeepEqual(got, want) {
		t.Errorf("files = %v, want %v", got, want)
	}
}

func TestWalkReadsOnlyGitignoreFiles(t *testing.T) {
	root := t.TempDir()
	write(t, root, map[string]string{
		".git/info/exclude": "local.go\n",
		"local.go":          "package p\n",
	})
	t.Setenv("GIT_DIR", filepath.Join(root, ".git"))
	want := []entry{{"local.go", Production}}
	if got := entries(walk(t, root, Options{})); !reflect.DeepEqual(got, want) {
		t.Errorf("files = %v, want %v, .git/info/exclude must not apply", got, want)
	}
}

func TestWalkSkipsGitAndNonRegularFiles(t *testing.T) {
	root := t.TempDir()
	write(t, root, map[string]string{
		".git/HEAD":    "ref\n",
		"sub/.git":     "gitdir: elsewhere\n",
		"sub/a.go":     "package sub\n",
		"linktarget/x": "x\n",
	})
	if err := os.Symlink(filepath.Join(root, "linktarget"), filepath.Join(root, "link")); err != nil {
		t.Fatal(err)
	}
	tree := walk(t, root, Options{})
	want := []entry{{"linktarget/x", Unsupported}, {"sub/a.go", Production}}
	if got := entries(tree); !reflect.DeepEqual(got, want) {
		t.Errorf("files = %v, want %v", got, want)
	}
}

func TestWalkNestedModules(t *testing.T) {
	root := t.TempDir()
	write(t, root, map[string]string{
		"go.mod":                        "module example.com/root // the root\n",
		"b/go.mod":                      "module example.com/root/b\n",
		"b/b.go":                        "package b\n",
		"a/go.mod":                      "module example.com/root/a\n",
		"testdata/fixture/go.mod":       "module example.com/fixture\n",
		"testdata/vendor/m/go.mod":      "module example.com/m\n",
		"gen/go.mod":                    "module example.com/root/gen\n",
		"testdata/fixture/f.go":         "package fixture\n",
		"vendor/example.com/v/go.mod":   "module example.com/v\n",
		"vendor/example.com/v/v.go":     "package v\n",
		".tools/go.mod":                 "module example.com/tools\n",
		"_old/go.mod":                   "module example.com/old\n",
		"c/go.mod/not-a-module-file.go": "package gomod\n",
	})
	tree := walk(t, root, Options{Exclude: []string{"gen/**"}})
	// A directory in the testdata, vendored, or excluded set is never a nested module.
	if want := []string{"a", "b"}; !reflect.DeepEqual(tree.NestedModules, want) {
		t.Errorf("nested modules = %v, want %v", tree.NestedModules, want)
	}
	want := []entry{
		{".tools/go.mod", Excluded},
		{"_old/go.mod", Excluded},
		{"c/go.mod/not-a-module-file.go", Production},
		{"gen/go.mod", Excluded},
		{"go.mod", Unsupported},
		{"testdata/fixture/f.go", Testdata},
		{"testdata/fixture/go.mod", Testdata},
		{"testdata/vendor/m/go.mod", Testdata},
		{"vendor/example.com/v/go.mod", Vendored},
		{"vendor/example.com/v/v.go", Vendored},
	}
	if got := entries(tree); !reflect.DeepEqual(got, want) {
		t.Errorf("files = %v, want %v", got, want)
	}
	if tree.Module != "example.com/root" {
		t.Errorf("module = %q, want example.com/root", tree.Module)
	}
}

func TestReadModule(t *testing.T) {
	cases := []struct {
		name  string
		gomod string
		want  string
	}{
		{"plain", "module example.com/a\n\ngo 1.23\n", "example.com/a"},
		{"quoted", "// header\nmodule \"example.com/b\"\n", "example.com/b"},
		{"comment", "module example.com/c // note\n", "example.com/c"},
		{"missing", "go 1.23\n", ""},
		{"prefix only", "modules x\n", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			root := t.TempDir()
			write(t, root, map[string]string{"go.mod": tc.gomod})
			got, err := readModule(root)
			if err != nil {
				t.Fatal(err)
			}
			if got != tc.want {
				t.Errorf("module = %q, want %q", got, tc.want)
			}
		})
	}
}

func TestWalkKeepsSyntaxOfMeasuredFiles(t *testing.T) {
	root := t.TempDir()
	write(t, root, map[string]string{
		"ok.go":  "package p\n\nfunc F() {}\n",
		"bad.go": "package p\n\nfunc (\n",
		"x.md":   "text\n",
	})
	tree := walk(t, root, Options{})
	for _, f := range tree.Files {
		switch f.Path {
		case "ok.go":
			if f.Syntax == nil || f.ParseErr != nil || len(f.Src) == 0 {
				t.Errorf("ok.go: syntax %v, error %v, %d source bytes", f.Syntax, f.ParseErr, len(f.Src))
			}
		case "bad.go":
			if f.ParseErr == nil {
				t.Error("bad.go: no parse error")
			}
		case "x.md":
			if f.Syntax != nil || f.Src != nil {
				t.Error("x.md: an unsupported file keeps no source")
			}
		}
	}
}

func TestWalkErrors(t *testing.T) {
	if _, err := Walk(context.Background(), filepath.Join(t.TempDir(), "missing"), Options{}); !errors.Is(err, fs.ErrNotExist) {
		t.Errorf("missing root: error %v, want fs.ErrNotExist", err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := Walk(ctx, filepath.Join(fixtures, "sets"), Options{}); !errors.Is(err, context.Canceled) {
		t.Errorf("cancelled context: error %v, want context.Canceled", err)
	}
}

func TestWalkRecordsUnreadableGoMod(t *testing.T) {
	root := t.TempDir()
	if err := os.Mkdir(filepath.Join(root, "go.mod"), 0o755); err != nil {
		t.Fatal(err)
	}
	tree := walk(t, root, Options{})
	want := []ReadError{{Path: "go.mod", Message: "read: is a directory"}}
	if !reflect.DeepEqual(tree.ReadErrors, want) {
		t.Errorf("read errors = %v, want %v", tree.ReadErrors, want)
	}
}

// realTempDir returns a temporary directory without symbolic links, as Walk reports its root.
func realTempDir(t *testing.T) string {
	t.Helper()
	root, err := filepath.EvalSymlinks(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	return root
}

// lock gives paths under root mode 000 until the test ends.
func lock(t *testing.T, root string, paths ...string) {
	t.Helper()
	if os.Geteuid() == 0 {
		t.Skip("root reads files with mode 000")
	}
	for _, path := range paths {
		abs := filepath.Join(root, filepath.FromSlash(path))
		if err := os.Chmod(abs, 0); err != nil {
			t.Fatal(err)
		}
		t.Cleanup(func() { _ = os.Chmod(abs, 0o755) })
	}
}

func TestWalkFollowsSymlinkedRoot(t *testing.T) {
	target := realTempDir(t)
	write(t, target, map[string]string{"go.mod": "module example.com/l\n", "a.go": "package l\n"})
	link := filepath.Join(t.TempDir(), "link")
	if err := os.Symlink(target, link); err != nil {
		t.Fatal(err)
	}
	want := shape{
		Root:          target,
		Module:        "example.com/l",
		Files:         []entry{{"a.go", Production}, {"go.mod", Unsupported}},
		NestedModules: []string{},
		Coverage:      zeroCoverage(map[SourceSet]int{Production: 1, Unsupported: 1}),
	}
	if got := shapeOf(walk(t, link, Options{})); !reflect.DeepEqual(got, want) {
		t.Errorf("tree:\n got %+v\nwant %+v", got, want)
	}
}

func TestWalkRecordsUnreadableGitignore(t *testing.T) {
	root := realTempDir(t)
	write(t, root, map[string]string{
		"g/.gitignore":        "secret.go\n",
		"g/secret.go":         "package g\n",
		"testdata/.gitignore": "x\n",
		"testdata/x":          "x\n",
	})
	lock(t, root, "g/.gitignore", "testdata/.gitignore")
	tree := walk(t, root, Options{})
	want := []ReadError{
		{Path: "g/.gitignore", Message: "open: permission denied"},
		{Path: "testdata/.gitignore", Set: Testdata, Message: "open: permission denied"},
	}
	if !reflect.DeepEqual(tree.ReadErrors, want) {
		t.Errorf("read errors = %+v, want %+v", tree.ReadErrors, want)
	}
	// The locked .gitignore gives no patterns, so the file it names is measured.
	if got, wantFiles := entries(tree), []entry{
		{"g/.gitignore", Excluded}, {"g/secret.go", Production}, {"testdata/.gitignore", Testdata}, {"testdata/x", Testdata},
	}; !reflect.DeepEqual(got, wantFiles) {
		t.Errorf("files = %v, want %v", got, wantFiles)
	}
}

func TestWalkRecordsUnsearchableDirectory(t *testing.T) {
	root := realTempDir(t)
	write(t, root, map[string]string{"r/a.go": "package r\n"})
	// A call to lock with no paths only skips the test for the root user.
	lock(t, root)
	if err := os.Chmod(filepath.Join(root, "r"), 0o400); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(filepath.Join(root, "r"), 0o755) })
	tree := walkWithin(t, root)
	// The walk can list the directory but cannot open anything in it.
	want := []ReadError{
		{Path: "r/.gitignore", Message: "lstat: permission denied"},
		{Path: "r/a.go", Message: "open: permission denied"},
	}
	if !reflect.DeepEqual(tree.ReadErrors, want) {
		t.Errorf("read errors = %+v, want %+v", tree.ReadErrors, want)
	}
}

func TestWalkRecordsSymlinkedGitignore(t *testing.T) {
	root := realTempDir(t)
	write(t, root, map[string]string{"patterns": "a.go\n", "a.go": "package p\n"})
	if err := os.Symlink(filepath.Join(root, "patterns"), filepath.Join(root, ".gitignore")); err != nil {
		t.Fatal(err)
	}
	tree := walkWithin(t, root)
	// Git does not follow a symbolic link named .gitignore, so a.go is measured.
	if want := []entry{{"a.go", Production}, {"patterns", Unsupported}}; !reflect.DeepEqual(entries(tree), want) {
		t.Errorf("files = %v, want %v", entries(tree), want)
	}
	want := []ReadError{{Path: ".gitignore", Message: "read: not a regular file"}}
	if !reflect.DeepEqual(tree.ReadErrors, want) {
		t.Errorf("read errors = %+v, want %+v", tree.ReadErrors, want)
	}
}

var errMidRead = errors.New("device error")

// failingReader returns its data, then fails every later read.
type failingReader struct{ data []byte }

func (r *failingReader) Read(p []byte) (int, error) {
	if len(r.data) == 0 {
		return 0, errMidRead
	}
	n := copy(p, r.data)
	r.data = r.data[n:]
	return n, nil
}

func TestIgnoreErrorRecordsAReadFailure(t *testing.T) {
	root := realTempDir(t)
	w := &walker{root: root, tree: &Tree{ReadErrors: []ReadError{}}}
	file := filepath.Join(root, "g", ".gitignore")
	// The handler adds the file name to the position, as the library does for a file that it opens.
	handler := func(e gitignore.Error) bool {
		p := e.Position()
		p.File = file
		return w.ignoreError(gitignore.NewError(e.Underlying(), p))
	}
	done := make(chan struct{})
	go func() {
		gitignore.New(&failingReader{data: []byte("a.go\nb")}, filepath.Dir(file), handler)
		close(done)
	}()
	select {
	case <-done:
	case <-time.After(5 * time.Second):
		t.Fatal("the parser did not stop after a failed read")
	}
	want := []ReadError{{Path: "g/.gitignore", Message: "device error"}}
	if !reflect.DeepEqual(w.tree.ReadErrors, want) {
		t.Errorf("read errors = %+v, want %+v", w.tree.ReadErrors, want)
	}
}

func TestIgnoreErrorDecisions(t *testing.T) {
	root := realTempDir(t)
	cases := []struct {
		name       string
		err        gitignore.Error
		wantResult bool
		wantErrors []ReadError
	}{
		{"invalid pattern", gitignore.NewError(gitignore.ErrInvalidPatternError, gitignore.Position{Line: 1}), true, []ReadError{}},
		{"carriage return", gitignore.NewError(gitignore.ErrCarriageReturnError, gitignore.Position{Line: 1}), true, []ReadError{}},
		{"missing file", gitignore.NewError(&fs.PathError{Op: "open", Path: filepath.Join(root, ".gitignore"), Err: fs.ErrNotExist}, gitignore.Position{}), true, []ReadError{}},
		{
			"failed open", gitignore.NewError(&fs.PathError{Op: "open", Path: filepath.Join(root, "d", ".gitignore"), Err: fs.ErrPermission}, gitignore.Position{}),
			false, []ReadError{{Path: "d/.gitignore", Message: "open: permission denied"}},
		},
		{"no file", gitignore.NewError(errMidRead, gitignore.Position{}), false, []ReadError{{Path: ".", Message: "device error"}}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			w := &walker{root: root, tree: &Tree{ReadErrors: []ReadError{}}}
			if got := w.ignoreError(tc.err); got != tc.wantResult {
				t.Errorf("result = %v, want %v", got, tc.wantResult)
			}
			if !reflect.DeepEqual(w.tree.ReadErrors, tc.wantErrors) {
				t.Errorf("read errors = %+v, want %+v", w.tree.ReadErrors, tc.wantErrors)
			}
		})
	}
}

// walkWithin fails the test when the walk does not end within five seconds.
// A loop inside the library never checks the context, so the walk runs in its own goroutine.
func walkWithin(t *testing.T, root string) *Tree {
	t.Helper()
	type result struct {
		tree *Tree
		err  error
	}
	done := make(chan result, 1)
	go func() {
		tree, err := Walk(context.Background(), root, Options{})
		done <- result{tree, err}
	}()
	select {
	case r := <-done:
		if r.err != nil {
			t.Fatalf("Walk(%s): %v", root, r.err)
		}
		return r.tree
	case <-time.After(5 * time.Second):
		t.Fatalf("Walk(%s) did not end within five seconds", root)
		return nil
	}
}

func TestWalkRecordsGitignoreThatIsNotAFile(t *testing.T) {
	root := realTempDir(t)
	write(t, root, map[string]string{"x/a.go": "package x\n", "x/.gitignore/inner": "a.go\n"})
	tree := walkWithin(t, root)
	wantFiles := []entry{{"x/.gitignore/inner", Excluded}, {"x/a.go", Production}}
	if got := entries(tree); !reflect.DeepEqual(got, wantFiles) {
		t.Errorf("files = %v, want %v", got, wantFiles)
	}
	want := []ReadError{{Path: "x/.gitignore", Message: "read: not a regular file"}}
	if !reflect.DeepEqual(tree.ReadErrors, want) {
		t.Errorf("read errors = %+v, want %+v", tree.ReadErrors, want)
	}
}

func TestWalkRecordsGitignoreFIFO(t *testing.T) {
	root := realTempDir(t)
	write(t, root, map[string]string{"a.go": "package p\n"})
	if err := syscall.Mkfifo(filepath.Join(root, ".gitignore"), 0o644); err != nil {
		t.Skipf("no FIFO on this platform: %v", err)
	}
	tree := walkWithin(t, root)
	if want := []entry{{"a.go", Production}}; !reflect.DeepEqual(entries(tree), want) {
		t.Errorf("files = %v, want %v", entries(tree), want)
	}
	want := []ReadError{{Path: ".gitignore", Message: "read: not a regular file"}}
	if !reflect.DeepEqual(tree.ReadErrors, want) {
		t.Errorf("read errors = %+v, want %+v", tree.ReadErrors, want)
	}
}

func TestWalkRecordsUnreadableRootGitignore(t *testing.T) {
	root := realTempDir(t)
	write(t, root, map[string]string{".gitignore": "a.go\n", "a.go": "package p\n"})
	lock(t, root, ".gitignore")
	tree := walkWithin(t, root)
	// The root has no path segment, so no path rule places the error in a set.
	want := []ReadError{{Path: ".gitignore", Message: "open: permission denied"}}
	if !reflect.DeepEqual(tree.ReadErrors, want) {
		t.Errorf("read errors = %+v, want %+v", tree.ReadErrors, want)
	}
}

func TestWalkRecordsUnlistableRoot(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root lists directories with mode 0311")
	}
	root := realTempDir(t)
	write(t, root, map[string]string{"a.go": "package p\n"})
	if err := os.Chmod(root, 0o311); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(root, 0o755) })
	tree := walkWithin(t, root)
	want := []ReadError{{Path: ".", Message: "open: permission denied"}}
	if !reflect.DeepEqual(tree.ReadErrors, want) {
		t.Errorf("read errors = %+v, want %+v", tree.ReadErrors, want)
	}
}

func TestWalkRecordsUnreadableEntries(t *testing.T) {
	root := realTempDir(t)
	write(t, root, map[string]string{
		"locked/a.go":          "package locked\n",
		"secret.go":            "package p\n",
		"testdata/locked/f.go": "package f\n",
		"z.go":                 "package p\n",
	})
	lock(t, root, "locked", "secret.go", "testdata/locked")
	tree := walk(t, root, Options{})
	want := shape{
		Root:          root,
		Files:         []entry{{"z.go", Production}},
		NestedModules: []string{},
		Coverage:      zeroCoverage(map[SourceSet]int{Production: 1}),
	}
	if got := shapeOf(tree); !reflect.DeepEqual(got, want) {
		t.Errorf("tree:\n got %+v\nwant %+v", got, want)
	}
	wantErrors := []ReadError{
		{Path: "locked", Message: "open: permission denied"},
		{Path: "secret.go", Message: "open: permission denied"},
		{Path: "testdata/locked", Set: Testdata, Message: "open: permission denied"},
	}
	if !reflect.DeepEqual(tree.ReadErrors, wantErrors) {
		t.Errorf("read errors = %v, want %v", tree.ReadErrors, wantErrors)
	}
}

func TestFinishShuffle(t *testing.T) {
	want := &Tree{
		Files:         []File{{Path: ".a"}, {Path: "a.go"}, {Path: "a/b.go"}, {Path: "a_test.go"}, {Path: "b"}},
		NestedModules: []string{"a", "a/b", "b", "c"},
		ReadErrors:    []ReadError{{Path: "a"}, {Path: "a/b"}, {Path: "b"}},
		Coverage:      map[SourceSet]SetCoverage{},
	}
	finish(want)
	for seed := int64(0); seed < 10; seed++ {
		r := rand.New(rand.NewSource(seed))
		got := &Tree{
			Files:         append([]File(nil), want.Files...),
			NestedModules: append([]string(nil), want.NestedModules...),
			ReadErrors:    append([]ReadError(nil), want.ReadErrors...),
			Coverage:      map[SourceSet]SetCoverage{},
		}
		r.Shuffle(len(got.Files), func(i, j int) { got.Files[i], got.Files[j] = got.Files[j], got.Files[i] })
		r.Shuffle(len(got.NestedModules), func(i, j int) {
			got.NestedModules[i], got.NestedModules[j] = got.NestedModules[j], got.NestedModules[i]
		})
		r.Shuffle(len(got.ReadErrors), func(i, j int) { got.ReadErrors[i], got.ReadErrors[j] = got.ReadErrors[j], got.ReadErrors[i] })
		finish(got)
		if !reflect.DeepEqual(got, want) {
			t.Fatalf("seed %d: order %+v, want %+v", seed, got, want)
		}
	}
}

// TestWalkOmit asserts that the omitted path leaves the walk and the coverage, however the path is spelled.
func TestWalkOmit(t *testing.T) {
	root := t.TempDir()
	write(t, root, map[string]string{"main.go": "package main\n", "out.json": "{}\n", "sub/out.json": "{}\n"})
	omits := map[string]string{
		"absolute": filepath.Join(root, "out.json"),
		"unclean":  filepath.Join(root, "sub", "..", "out.json"),
		"missing":  filepath.Join(root, "absent.json"),
	}
	want := map[string][]entry{
		"absolute": {{"main.go", Production}, {"sub/out.json", Unsupported}},
		"unclean":  {{"main.go", Production}, {"sub/out.json", Unsupported}},
		"missing":  {{"main.go", Production}, {"out.json", Unsupported}, {"sub/out.json", Unsupported}},
	}
	for name, omit := range omits {
		t.Run(name, func(t *testing.T) {
			tree := walk(t, root, Options{Omit: omit})
			if got := entries(tree); !reflect.DeepEqual(got, want[name]) {
				t.Errorf("files = %v, want %v", got, want[name])
			}
		})
	}
}

// TestWalkOmitThroughSymlink asserts that an omit path under a symbolic link to the root still matches.
func TestWalkOmitThroughSymlink(t *testing.T) {
	root := t.TempDir()
	write(t, root, map[string]string{"out.json": "{}\n"})
	link := filepath.Join(t.TempDir(), "link")
	if err := os.Symlink(root, link); err != nil {
		t.Skip(err)
	}
	tree := walk(t, link, Options{Omit: filepath.Join(link, "out.json")})
	if got := entries(tree); len(got) != 0 {
		t.Errorf("files = %v, want none", got)
	}
}
